
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - 'c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface SitePreferences {
			/**
			* Queue-it Customer Id

				Your Queue-it customer ID. Find it in GO Self-service platform, under Account -> Company Profile.
			* @group queueit - Queue-it Configurations
			* @source [attribute](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#5) | [group](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#59)
			*/
			['queueit-customerId']: string | null;

			/**
			* Queue-it enabled

				Should Queue-it be enabled for the selected site.
			* @group queueit - Queue-it Configurations
			* @source [attribute](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#13) | [group](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#58)
			*/
			['queueit-enabled']: boolean | null;

			/**
			* Enable Enqueue Token

				Must also be enabled and configured in GO self-service platform. Reach out to Queue-it customer service for more info.
			* @group queueit - Queue-it Configurations
			* @source [attribute](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#21) | [group](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#61)
			*/
			['queueit-enableEnqueueToken']: boolean | null;

			/**
			* Enable QueueIt Logging

				Enable logging to log queue-it data.
			* @group queueit - Queue-it Configurations
			* @source [attribute](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#29) | [group](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#62)
			*/
			['queueit-enableLogging']: boolean | null;

			/**
			* Queue-it Integrations Config string

				Your integration config as JSON string. Find it in GO Self-service platform, under Integration -> Show/Hide instructions -> Manually download the configuration file -> Download.
			* @group queueit - Queue-it Configurations
			* @source [attribute](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#37) | [group](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#63)
			*/
			['queueit-integrationsConfigString']: string | null;

			/**
			* Queue-it Secret Key

				Your 72 char KnownUser secret key. Find it in GO Self-service platform, under Account -> Settings -> Integration.
			* @group queueit - Queue-it Configurations
			* @source [attribute](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#46) | [group](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#60)
			*/
			['queueit-secretKey']: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* Queue-it Customer Id

				Your Queue-it customer ID. Find it in GO Self-service platform, under Account -> Company Profile.
			* @group queueit - Queue-it Configurations
			* @source [attribute](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#5) | [group](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#59)
			*/
			(name: 'queueit-customerId'): string | null;
			
			/**
			* Queue-it enabled

				Should Queue-it be enabled for the selected site.
			* @group queueit - Queue-it Configurations
			* @source [attribute](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#13) | [group](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#58)
			*/
			(name: 'queueit-enabled'): boolean | null;
			
			/**
			* Enable Enqueue Token

				Must also be enabled and configured in GO self-service platform. Reach out to Queue-it customer service for more info.
			* @group queueit - Queue-it Configurations
			* @source [attribute](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#21) | [group](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#61)
			*/
			(name: 'queueit-enableEnqueueToken'): boolean | null;
			
			/**
			* Enable QueueIt Logging

				Enable logging to log queue-it data.
			* @group queueit - Queue-it Configurations
			* @source [attribute](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#29) | [group](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#62)
			*/
			(name: 'queueit-enableLogging'): boolean | null;
			
			/**
			* Queue-it Integrations Config string

				Your integration config as JSON string. Find it in GO Self-service platform, under Integration -> Show/Hide instructions -> Manually download the configuration file -> Download.
			* @group queueit - Queue-it Configurations
			* @source [attribute](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#37) | [group](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#63)
			*/
			(name: 'queueit-integrationsConfigString'): string | null;
			
			/**
			* Queue-it Secret Key

				Your 72 char KnownUser secret key. Find it in GO Self-service platform, under Account -> Settings -> Integration.
			* @group queueit - Queue-it Configurations
			* @source [attribute](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#46) | [group](file:c:\queueit\Repos\KnownUser.V3.SalesForceCC-SFRA\cartridges\int_queueit_sfra\metadata\meta\system-objecttype-extensions.xml#60)
			*/
			(name: 'queueit-secretKey'): string | null;
			
	}
}